env:
  es6: true
  node: true
  jest: true
extends:
- 'plugin:@typescript-eslint/recommended'
- 'plugin:prettier/recommended'

parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  no-console:
    - warn
  '@typescript-eslint/no-explicit-any':
    - warn
  '@typescript-eslint/camelcase':
    - off
  prettier/prettier:
    - error
    - singleQuote: true

